### ISSUE TITLE
Juarez - OCW24 - Migrate Micronaut + JDK + Jakarta EE (ISSUES) - A Java Microservice with GraalVM, Micronaut Data, JDK 21, and the Oracle Autonomous Database

### ISSUE THREAD

**Issue by juarezjuniorgithub** [Kuassim/Kuassim#462]

**Comment by juarezjuniorgithub** [comment]
1) FIRST ISSUE - SOLVED

Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
Unable to implement Repository method: ThingRepository.delete(Object entity). Cannot query persistentEntity [Thing] on non-existent property: entity

**Comment by juarezjuniorgithub** [comment]
2) SECOND ISSUE - SOLVED

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.4.1:enforce (micronaut-enforce) on project
 micronautguide:
[ERROR] Rule 1: io.micronaut.maven.enforcer.CheckSnakeYaml failed with message:
[ERROR] YAML configuration file detected, but SnakeYAML is not on the runtime classpath. Make sure to add the following dependency:
[ERROR] <dependency>
[ERROR]   <groupId>org.yaml</groupId>
[ERROR]   <artifactId>snakeyaml</artifactId>
[ERROR]   <scope>runtime</scope>
[ERROR] </dependency>

**Comment by juarezjuniorgithub** [comment]
3) THIRD ISSUED - SOLVED 

Caused by: java.lang.IllegalArgumentException: The argument does not represent an annotation type: NotBlank
https://micronaut.io/2023/05/09/upgrade-to-micronaut-framework-4-0-0/

**Comment by juarezjuniorgithub** [comment]
4) FOURTH ISSUE - SOLVED

19:02:11.948 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Found non-empty schema(s) "ADMIN" but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Found non-empty schema(s) "ADMIN" but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1982)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:294)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3348)
        at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3692)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:342)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:202)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:74)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:328)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:314)
        at com.oracle.dev.jdbc.micronaut.Application.main(Application.java:8)

**Comment by juarezjuniorgithub** [comment]
5) FIFTH - UPGRADED micronaut-sourcegen-*
https://mvnrepository.com/artifact/io.micronaut.sourcegen

**Comment by juarezjuniorgithub** [comment]
6) SIXTH - SOLVED 

18:46:25.984 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error executing SQL UPDATE: ORA-00942: table or view does not exist
io.micronaut.data.exceptions.DataAccessException: Error executing SQL UPDATE: ORA-00942: table or view does not exist

**Comment by juarezjuniorgithub** [comment]
7) FINAL ADJUSTMENTS + TESTS (VALIDATION) - COMPLETED ***

Migrate to Micronaut 4.4.2 + Jakarta EE + JDK 22
Solve all the issues (dependencies, versions) after migration (mandated by Micronaut, which uses Jakarta EE in the latest version)
Revamped application.properties
Removed application*.yml (REMOVE AMBIGUITY)
Revamped DataPopulator.java
Revamped pom.xml
Adjusted the blog post to add more details (micronaut and DB23ai links, wallet, flyway citation, sql script citation)
